### ISSUE TITLE
Request of merging to upstream.

### ISSUE THREAD

**Issue by ghost** [DuckVador/qvssr#1]
Same as title.
Qv2ray is currently maintained by a group of people, where merging those features will benefit both the potential QvSSR users and current Qv2ray users and reduce the difficulty to maintain.

**Comment by darsvador** [comment]
To support other operating systems other than Linux, qvssr needs to gradually replace the dependencies of ssr-libev until all dependencies are completely cross-platform. This requires a lot of work. Of course, after this work is completed, I will merge the code upstream as soon as possible.

**Comment by ghost** [comment]
Thanks!
We'd love to see that day coming.
